name: info_safety_lab2
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: 6.0.3
  collection: 1.16.0
  path_provider: 2.0.11
  dart_des: 1.0.0
  crypto: 3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
